---
title: NanoTwitter introduced
desc: Get explanation of what nanoTwitter is and how it will work.
slides: true
cat: web
---
:h3 All About nano Twitter

1. :topic_link :nt_functionality -- Point by point requirements for the project that everyone will be doing, nanoTwitter
1. :topic_link :nt_arch -- Review of key technical points of architecture and process
1. :topic_link :nt_outline -- Approximate sequence of steps to get to the finished product

:lecture_end
