---
title: Testing in the world of SOA
desc: Testing, Unit Testing and special cases in SOA
cat: scale
slides: true
---
:h3 Logistics
* Secret code is:
* Masks may be off if you are tripple vaxed and healthy
* How did it go with Authentication?

:topic_include :testing_services

:slide_bigtitle Additional material
* :topic_link :money_class_test_example
* :topic_link :mocking
* :topic_link :testing_data
* :topic_link :testing_reasons

:lecture_end
