---
title: Service Oriented Architecture
desc: We start going in to more complicated core architectures
cat: nt
slides: true
---
:h3 Review 

* Let's take a look at this active_record example: [sinatra_activerecord_sample](https://github.com/pitosalas/public_samples/tree/master/sinatra/sinatra_activerecord_sample)

:topic_include :soa_architecture
:topic_include :sinatra_technology_options

:lecture_end
